### ISSUE TITLE
Taxonomy values of numbers (even with quotes) are not recognised

### ISSUE THREAD

**Issue by jkelleher** [getgrav/grav-plugin-taxonomylist#1]
With a taxonomy value of (say):
```
tag: 171
```
Then this:
```{% set taxlist = taxonomylist.get() %}
{% for tax,value in taxlist['tag'] %}
        <a href="#">{{ tax }} => {{ value }}</a>
    {% endfor %}
```
yields: `0 => 1`
Even using `tag: b171` makes it work yielding: `b171 => 1`

**Comment by rhukster** [comment]
Sorted with https://github.com/getgrav/grav-plugin-taxonomylist/commit/21fe4f03e99eefb566025b286fd845d160bd1c57
