### ISSUE TITLE
How to exclude tags

### ISSUE THREAD

**Issue by Endogen** [getgrav/grav-plugin-taxonomylist#10]
I'd like to exclude a specific tag from the list. How could i do this? Background: I use the [private plugin](https://github.com/Diyzzuf/grav-plugin-private) and that depends on pages that have the tag ```hidden```and i don't want this tag to show up in the taxonomylist plugin

**Comment by flaviocopes** [comment]
What you can do is override the https://github.com/getgrav/grav-plugin-taxonomylist/blob/develop/templates/partials/taxonomylist.html.twig twig template in your theme, and check for that specific tag in an "if"

**Comment by Endogen** [comment]
Thanks! Works great
