### ISSUE TITLE
Not working + missing example. Possible workaround to both issues.

### ISSUE THREAD

**Issue by fabrizioT** [getgrav/grav-plugin-taxonomylist#14]
I've spent some time in figuring how to get this working, as no example was given ...
Unless i'm wrong i guess you are supposed to traverse the taxonomy list from Twig via some code like:

`{% for name,count in taxonomylist.category %} 
  taxonomy name:{{name}} - number of posts:({{count}}) 
{% endfor %}`

However i was unable to get the list populated.
I do think function **onTwigSiteVariables()** within **taxonomylist.php** is broken / uncomplete.

Seems to me it simply lacks the proper getter call, so generated list is always empty.
The plugin works when i add this (ugly) call at the bottom of onTwigSiteVariables() function:

`$twig->twig_vars['taxonomylist'] = $twig->twig_vars['taxonomylist']->get();`

I stand corrected.

**Comment by fabrizioT** [comment]
Nevermind.
Getter should be explicitly called, so the plugin will work straight out-of-the-box.

Found a working example here:
http://diblas.net/blog/add-the-posts-categories-to-the-blog-navigation-menu-powered-by-grav-cms

`{% set taxlist = taxonomylist.get() %}
{% if taxlist %}
    {% for tax,value in taxlist['category'] %}
    <li>
        <a href="{{ base_url }}/category{{ config.system.param_sep }}{{ tax|e('url') }}">{{ tax|capitalize }}</a>
    </li>
    {% endfor %}
{% endif %}`

**Comment by onetrev** [comment]
The link above goes to a SPAM site. It should be removed immediately.

**Comment by MakaryGo** [comment]
> The link above goes to a SPAM site. It should be removed immediately.

That's true, however I did manage to find original content on Wayback Machine :
https://web.archive.org/web/20180207164318/http://diblas.net/blog/add-the-posts-categories-to-the-blog-navigation-menu-powered-by-grav-cms#

**Comment by ricardo118** [comment]
removed the spam link
