### ISSUE TITLE
Please change to tax|lower

### ISSUE THREAD

**Issue by campino2k** [getgrav/grav-plugin-taxonomylist#18]
https://github.com/getgrav/grav-plugin-taxonomylist/blob/1d6b089b213d60a7af8d0017d8d24cb2d2569df5/templates/partials/taxonomylist.html.twig#L6

This breaks with Grav 1.3.8 since `uri.param` will return lowercase strings

**Comment by rhukster** [comment]
Thanks, merged

**Comment by rhukster** [comment]
and released

**Comment by rhukster** [comment]
Along with that other PR, i'm seeing that this doesn't actually need to be lowercased anymore.  please make sure you have `case_insensitive_urls` in your system.yaml removed or set to `false`.
