### ISSUE TITLE
Cache always bypassed

### ISSUE THREAD

**Issue by pamtbaau** [getgrav/grav-plugin-taxonomylist#23]
In commit [c1335ea](https://github.com/getgrav/grav-plugin-taxonomylist/commit/c1335ea87cc6551a8c0d54446b332dd07821e743#diff-03a62f2c3814c9cc152e6a4e6dba43c2) cache was introduced:
```
if ($taxonomy = $cache->fetch($hash)) {
    return $taxonomy;
} else {
```

In commit [1d6b089](https://github.com/getgrav/grav-plugin-taxonomylist/commit/1d6b089b213d60a7af8d0017d8d24cb2d2569df5#diff-03a62f2c3814c9cc152e6a4e6dba43c2) it has been defunct... (for testing purposes?)
```
if ($taxonomy = $cache->fetch($hash . 'x')) {
    return $taxonomy;
} else {
```

**Comment by rhukster** [comment]
Released.. Thanks!
