### ISSUE TITLE
Issue with "YAML Compatibility" to "off" when re-installing Plugin?

### ISSUE THREAD

**Issue by paulhibbitts** [getgrav/grav-plugin-taxonomylist#29]
I've been testing my themes with "YAML Compatibility" to "Off" to help prepare for Grav 2.x, and I've been seeing this error when I try to update my Bootstrap4 Open Matter theme:

![taxonomylist-blueprint](https://user-images.githubusercontent.com/1812771/64043961-8d328f80-cb1a-11e9-947f-96d65b8ca3be.png)

Might there be an issue with the Blueprint for the Taxonomy List that causes this?

Thanks very much,
Paul
ps - looks like this error happens when a theme has the Taxonomy Plugin as a dependency, when  "YAML Compatibility" to "Off" (error also happens with my Quark Open Publishing theme)

**Comment by rhukster** [comment]
https://github.com/getgrav/grav-plugin-taxonomylist/commit/efdde8e5a24b4e13ff947fbffa6fda30b39bbbfb

**Comment by paulhibbitts** [comment]
Thanks very much Andy!
