### ISSUE TITLE
Links generated by plugin route to the homepage and not the blog

### ISSUE THREAD

**Issue by bovisp** [getgrav/grav-plugin-taxonomylist#3]
I am using this plugin with its default twig file and yaml config file.

The issue is that when I click on one of the links that is generated by this plugin, it just routes me back to my homepage. You can see this in action on my [Koding VM](http://u5kke0983cf3.5to9design.koding.io/grav).

It also seems that `tag` is hard coded so you can't use another taxonomy such as `category` or another custom taxonomy.

**Comment by rhukster** [comment]
Even though you did provide a PR for this with a config option, I think the best solution is to pass the values for taxonomy and base_url when you include the partial. For example:

```
{% include 'partials/taxonomylist.html.twig' with {'taxonomy':'tag', 'base_url', `/blog`} %}
```
