### ISSUE TITLE
Fix not included in GPM release

### ISSUE THREAD

**Issue by MakaryGo** [getgrav/grav-plugin-taxonomylist#32]
Fix efdde8e is apparently not included in latest plugin version in GPM

**Comment by MakaryGo** [comment]
**Still** does not work, despite the issue being fixed in the repository.

```
Yaml Linter
===========

user/plugins/taxonomylist/
--------------------------


 [ERROR] YAML Linting issues found...


user/plugins/taxonomylist/blueprints.yaml - Found unknown escape character "\-" at line 34 (near "pattern: "/([a-z\-_]+/?)+"").
```

**Comment by mahagr** [comment]
Can you try `pattern: '/([a-z_-]+/?)+'`

**Comment by MakaryGo** [comment]
@mahagr sure, it works :) But my problem is that it is fixed _in this repository_, it **isn't in the GPM**. Because of this, I have to manually patch it every time I use this plugin, or a skeleton that has it listed as a dependency (mostly hibbitts-design/grav-theme-quark-open-publishing); otherwise it throws the above error during update.

**Comment by rhukster** [comment]
Sorry, not sure how this never got released!  Released now for next GPM update.
