### ISSUE TITLE
Extra Dead Tag

### ISSUE THREAD

**Issue by umbergerba** [getgrav/grav-plugin-taxonomylist#6]
This is showing-up across all my GRAV sites (see attachment). I've double checked all tags, and even removed them, no difference.

Suggestions?

![screen shot 2015-08-07 at 4 20 51 pm](https://cloud.githubusercontent.com/assets/5008228/9146224/895f5c1c-3d20-11e5-9816-614d0b9d9ccf.png)

**Comment by K232** [comment]
Are you using Grav Admin Panel? I've noticed the same on a page which previously had no tag. When I edited it in admin panel, an empty tag has been added to the page and therefore appears in the taxonomy list. Removing the tag from the page without admin panel fixed the problem.

**Comment by umbergerba** [comment]
Yes, I'm using Admin Panel, Ill check out your idea. THX!

**Comment by umbergerba** [comment]
Ok, I tried your suggestion and I could not find any "empty tags".

Suggestions?

**Comment by K232** [comment]
The fix #7 mentioned above works fine for me. Maybe add this on your own as long as it's not implemented in the official version.

**Comment by rhukster** [comment]
I've actually fixed this in the admin plugin so it doesn't even save empty taxonomies.  This will not be needed after the next update of the admin plugin.

**Comment by umbergerba** [comment]
Great ... THX!
