### ISSUE TITLE
Pulling taxonomies of non-visible pages

### ISSUE THREAD

**Issue by knurdtech** [getgrav/grav-plugin-taxonomylist#8]
It appears to be getting the tags of pages set to "published: false."

Therefore, tags are being published on the sidebar that lead to no content when clicked.

**Comment by flaviocopes** [comment]
Should not happen. The taxonomies list is cached. 
Did you clear the Grav cache after unpublishing the page?

**Comment by knurdtech** [comment]
You're right. I found the tags were coming from a "visible: false" page...not a "published: false" page. I removed the tags from that page to fix it.
